AWSTemplateFormatVersion: '2010-09-09'

Description: ECR repository for the Collectory service

Parameters:
  pBuild:
    Type: String
    Description: The build number
  pCleanBranch:
    Type: String
    Description: The clean branch, can be used in resource names
  pEnvironment:
    Type: String
    Description: The AWS environment this belongs to

Conditions:

  IsDev: !Equals
    - !Ref pEnvironment
    - development
  NotProd: !Not
    - !Equals
      - !Ref pEnvironment
      - production
  IsFirstBuild: !Equals [!Ref pBuild, "1"]

Resources:

  CollectoryRepository:
    Type: AWS::ECR::Repository
    Properties:
      EmptyOnDelete: !If [ NotProd, true, false ]
      EncryptionConfiguration:
        EncryptionType: AES256
      ImageScanningConfiguration:
        ScanOnPush: true
      RepositoryName: !Sub
                         - collectory-${ResourceName}
                         - ResourceName: !If [ IsDev, !Ref pCleanBranch, !Ref pEnvironment ]
      RepositoryPolicyText:
        Version: 2012-10-17
        Statement:
          - Sid: AllowPublicPull
            Effect: Allow
            Principal: '*'
            Action:
              - 'ecr:GetDownloadUrlForLayer'
              - 'ecr:BatchGetImage'
              - 'ecr:BatchCheckLayerAvailability'
      Tags:
        - Key: Environment
          Value: !Ref pEnvironment
        - Key: Branch
          Value: !Ref pCleanBranch

Outputs:

  CollectoryRepositoryArn:
    Description: The ECR repository ARN for the Collectory service
    Value: !GetAtt CollectoryRepository.Arn

  CollectoryRepositoryUri:
    Description: The ECR repository URI for the Collectory service
    Value: !GetAtt CollectoryRepository.RepositoryUri
    Export:
      Name: !Sub ${AWS::StackName}-CollectoryRepositoryUri

  CollectoryRepositoryName:
    Description: The ECR repository name for the Collectory service
    Value: !Ref CollectoryRepository
