services:

  mysqldb:
    image: mysql:5.7
    volumes:
      - db_data_collectory:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: collectory
      MYSQL_USER: collectory
      MYSQL_PASSWORD: collectory
    ports:
      - 3306:3306

  collectory:
    depends_on:
      - mysqldb
    image: sbdi/collectory-dev
    build:
      context: .
    ports:
      - 8080:8080
    volumes:
      - ./sbdi/data/config/collectory-config.properties:/data/collectory/config/collectory-config.properties

volumes:
  db_data_collectory:
