---
version: '3.8'

services:
  collectory:
    container_name: living-atlas-collectory
    image: livingatlases/collectory:latest
    pull_policy: if_not_present
    restart: always

    ports:
      - 9284:8080
    volumes:
      - /data:/data

  mysql:
    container_name: living-atlas-collectory-mysql
    image: mysql:8
    ports:
      - 3306
    volumes:
      - /data/dbs/collectory-mysql-data:/var/lib/mysql
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: collectory
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: collectory
      # DB_DUMP_PATH: "some-dump.sql"

networks:
  default:
    name: living-atlas-collectory
