openapi: "3.0.0"
info:
  title: "Registry service"
  description: "Web services for the Registry"
  version: "1.0"
  contact:
    name: "ALA Support"
    url: "http://www.ala.org.au/"
    email: "support@ala.org.au"
  license:
    name: "ALA licence"
    url: "http://www.ala.org.au/"
servers:
  - url: /ws
    description: Registry Base URL
paths:
  /dataResource:
    post:
      security:
        - bearerAuth: []
      summary: Create Data Resource
      description: Create a new Data Resource
      requestBody:
        description: JSON map of properties
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DataResource'
      tags:
        - Data resource
      responses:
        200:
          description: 'Search results'
  /dataResource/{uid}:
    get:
      summary: Get Data Resource
      description: Create a new Data Resource
      parameters:
        - in: path
          name: uid
          schema:
            type: string
          required: true
          description: UID for the data resource
      tags:
        - Data resource
      responses:
        200:
          description: 'Search results'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataResource'
    post:
      security:
        - bearerAuth: []
      summary: Update Data Resource
      description: Update a new Data Resource
      parameters:
        - in: path
          name: uid
          schema:
            type: string
          required: true
          description: UID for the data resource
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DataResource'
      tags:
        - Data resource
      responses:
        200:
          description: 'Search results'
    delete:
      security:
        - bearerAuth: []
      summary: Delete Data Resource
      description: Create a new Data Resource
      parameters:
        - in: path
          name: uid
          schema:
            type: string
          required: true
          description: UID for the data resource
      tags:
        - Data resource
      responses:
        200:
          description: 'Search results'
  /dataProvider:
    post:
      security:
        - bearerAuth: []
      summary: Create Data Resource
      description: Create a new Data Resource
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DataProvider'
      tags:
        - Data provider
      responses:
        200:
          description: 'Search results'
  /dataProvider/{uid}:
    get:
      summary: Get Data Provider
      description: Create a new Data Provider
      parameters:
        - in: path
          name: uid
          schema:
            type: string
          required: true
          description: UID for the data provider
      tags:
        - Data provider
      responses:
        200:
          description: 'Search results'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataProvider'
    post:
      security:
        - bearerAuth: []
      summary: Update Data provider
      description: Create a new Data provider
      parameters:
        - in: path
          name: uid
          schema:
            type: string
          required: true
          description: UID for the data provider
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DataProvider'
      tags:
        - Data provider
      responses:
        200:
          description: 'Search results'
    delete:
      security:
        - bearerAuth: []
      summary: Delete Data Provider
      description: Create a new Data provider
      parameters:
        - in: path
          name: uid
          schema:
            type: string
          required: true
          description: UID for the data resource
      tags:
        - Data provider
      responses:
        200:
          description: 'Search results'
  /institution:
    post:
      security:
        - bearerAuth: []
      summary: Create Institution
      description: Create a new Institution
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Institution'
      tags:
        - Institution
      responses:
        200:
          description: 'Search results'
  /institution/{uid}:
    get:
      summary: Get institution
      description: Create a new institution
      parameters:
        - in: path
          name: uid
          schema:
            type: string
          required: true
          description: UID for the Institution
      tags:
        - Institution
      responses:
        200:
          description: 'Search results'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Institution'
    post:
      summary: Update institution
      description: Create a new institution
      parameters:
        - in: path
          name: uid
          schema:
            type: string
          required: true
          description: UID for the Institution
      tags:
        - Institution
      responses:
        200:
          description: 'Search results'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Institution'
    delete:
      security:
        - bearerAuth: []
      summary: Delete Institution
      description: Create a new Institution
      parameters:
        - in: path
          name: uid
          schema:
            type: string
          required: true
          description: UID for the Institution
      tags:
        - Institution
      responses:
        200:
          description: 'Search results'
  /collection:
    post:
      security:
        - bearerAuth: []
      summary: Create Collection
      description: Create a new Collection
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Collection'
      tags:
        - Collection
      responses:
        200:
          description: 'Search results'
  /collection/{uid}:
    get:
      summary: Get collection
      description: Create a new collection
      parameters:
        - in: path
          name: uid
          schema:
            type: string
          required: true
          description: UID for the collection
      tags:
        - Collection
      responses:
        200:
          description: 'Search results'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Collection'
    post:
      summary: Update collection
      description: Create a new collection
      parameters:
        - in: path
          name: uid
          schema:
            type: string
          required: true
          description: UID for the collection
      tags:
        - Collection
      responses:
        200:
          description: 'Search results'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Collection'
    delete:
      security:
        - bearerAuth: []
      summary: Delete Collection
      description: Delete Collection
      parameters:
        - in: path
          name: uid
          schema:
            type: string
          required: true
          description: UID for the Collection
      tags:
        - Collection
      responses:
        200:
          description: 'Search results'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    DataResource:
      description: Data Resource metadata in JSON
      type: object
      properties:
        name:
          type: string
        acronym:
          type: string
        uid:
          type: string
        guid:
          type: string
        address:
          type: object
          properties:
            street:
              type: string
            city:
              type: string
            state:
              type: string
            postcode:
              type: string
            country:
              type: string
            postBox:
              type: string
        phone:
          type: string
        email:
          type: string
        pubShortDescription:
          type: string
        pubDescription:
          type: string
        techDescription:
          type: string
        focus:
          type: string
        latitude:
          type: number
        longitude:
          type: number
        state:
          type: string
        websiteUrl:
          type: string
        dateCreated:
          type: string
        lastUpdated:
          type: string
        userLastModified:
          type: string
        rights:
          type: string
        licenseType:
          type: string
        licenseVersion:
          type: string
        citation:
          type: string
        resourceType:
          type: string
        dataGeneralizations:
          type: string
        informationWithheld:
          type: string
        permissionsDocument:
          type: string
        permissionsDocumentType:
          type: string
        status:
          type: string
        provenance:
          type: string
        harvestFrequency:
          type: string
        lastChecked:
          type: string
        dataCurrency:
          type: string
        harvestingNotes:
          type: string
        gbifDataset:
          type: boolean
        isShareableWithGBIF:
          type: boolean
        verified:
          type: boolean
        gbifRegistryKey:
          type: string
        doi:
          type: string
    DataProvider:
      description: Data Provider metadata in JSON
      type: object
      properties:
        name:
          type: string
        acronym:
          type: string
        uid:
          type: string
        guid:
          type: string
          format: nullable
        address:
          type: string
          format: nullable
        phone:
          type: string
          format: nullable
        email:
          type: string
          format: nullable
        pubShortDescription:
          type: string
          format: nullable
        pubDescription:
          type: string
          format: nullable
        techDescription:
          type: string
          format: nullable
        focus:
          type: string
          format: nullable
        state:
          type: string
          format: nullable
        websiteUrl:
          type: string
          format: nullable
        alaPublicUrl:
          type: string
        logoRef:
          type: object
          properties:
            filename:
              type: string
            caption:
              type: string
              format: nullable
            copyright:
              type: string
              format: nullable
            attribution:
              type: string
              format: nullable
            uri:
              type: string
        networkMembership:
          type: string
          format: nullable
        attributions:
          type: array
          items:
            type: object
        dateCreated:
          type: string
          format: date-time
        lastUpdated:
          type: string
          format: date-time
        userLastModified:
          type: string
        dataResources:
          type: array
          items:
            type: object
        gbifRegistryKey:
          type: string

    Institution:
      description: Institution metadata in JSON
      properties:
        name:
          type: string
        acronym:
          type: string
        uid:
          type: string
        guid:
          type: string
        address:
          type: string
          format: nullable
        phone:
          type: string
          format: nullable
        email:
          type: string
          format: nullable
        pubShortDescription:
          type: string
          format: nullable
        pubDescription:
          type: string
        techDescription:
          type: string
        focus:
          type: string
          format: nullable
        state:
          type: string
          format: nullable
        websiteUrl:
          type: string
        alaPublicUrl:
          type: string
        imageRef:
          type: object
          properties:
            filename:
              type: string
            caption:
              type: string
            copyright:
              type: string
            attribution:
              type: string
              format: nullable
            uri:
              type: string
        logoRef:
          type: object
          properties:
            filename:
              type: string
            caption:
              type: string
              format: nullable
            copyright:
              type: string
            attribution:
              type: string
              format: nullable
            uri:
              type: string
        networkMembership:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              acronym:
                type: string
              logo:
                type: string
        hubMembership:
          type: array
          items:
            type: object
            properties:
              uid:
                type: string
              name:
                type: string
              uri:
                type: string
        dateCreated:
          type: string
          format: date-time
        lastUpdated:
          type: string
          format: date-time
        userLastModified:
          type: string
        institutionType:
          type: string
        collections:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              uri:
                type: string
              uid:
                type: string
              id:
                type: integer
                format: int32
        parentInstitutions:
          type: array
        childInstitutions:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              uri:
                type: string
              uid:
                type: string
              id:
                type: integer
                format: int32
        linkedRecordProviders:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              uri:
                type: string
              uid:
                type: string
        gbifRegistryKey:
          type: string
    Collection:
      description: Collection metadata in JSON
      properties:
        name:
          type: string
        acronym:
          type: string
        uid:
          type: string
        guid:
          type: string
        address:
          type: object
          properties:
            street:
              type: string
            city:
              type: string
            state:
              type: string
            postcode:
              type: string
            country:
              type: string
            postBox:
              type: string
        phone:
          type: string
          format: nullable
        email:
          type: string
          format: nullable
        pubShortDescription:
          type: string
          format: nullable
        pubDescription:
          type: string
        techDescription:
          type: string
        focus:
          type: string
          format: nullable
        latitude:
          type: number
        longitude:
          type: number
        state:
          type: string
          format: nullable
        websiteUrl:
          type: string
        alaPublicUrl:
          type: string
        imageRef:
          type: object
          properties:
            filename:
              type: string
            caption:
              type: string
            copyright:
              type: string
            attribution:
              type: string
              format: nullable
            uri:
              type: string
        networkMembership:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              acronym:
                type: string
              logo:
                type: string
        hubMembership:
          type: array
          items:
            type: object
            properties:
              uid:
                type: string
              name:
                type: string
              uri:
                type: string
        taxonomyCoverageHints:
          type: array
          items:
            type: object
            properties:
              phylum:
                type: string
        attributions:
          type: array
        dateCreated:
          type: string
          format: date-time
        lastUpdated:
          type: string
          format: date-time
        userLastModified:
          type: string
        collectionType:
          type: array
          items:
            type: string
        keywords:
          type: array
          items:
            type: string
        active:
          type: string
        numRecords:
          type: integer
          format: int32
        numRecordsDigitised:
          type: integer
          format: int32
        states:
          type: string
        geographicDescription:
          type: string
          format: nullable
        startDate:
          type: string
        endDate:
          type: string
          format: nullable
        kingdomCoverage:
          type: array
          items:
            type: string
        scientificNames:
          type: array
          items:
            type: string
        subCollections:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              description:
                type: string
        institution:
          type: object
          properties:
            name:
              type: string
            uri:
              type: string
            uid:
              type: string
        recordsProviderMapping:
          type: object
          properties:
            collectionCodes:
              type: array
              items:
                type: string
            institutionCodes:
              type: array
              items:
                type: string
            matchAnyCollectionCode:
              type: boolean
            exact:
              type: boolean
            warning:
              type: string
              format: nullable
            dateCreated:
              type: string
              format: date-time
            lastUpdated:
              type: string
              format: date-time
        linkedRecordProviders:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              uri:
                type: string
              uid:
                type: string
        gbifRegistryKey:
          type: string
          format: nullable
tags:
  - name: Data resource
    description: Services for Data resources
