version: 0.2
###
# This build project builds the Collectory UI site files ready for upload to s3

env:
  shell: bash

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: $NODE_VERSION
    commands:
      - echo injecting session auth config
      - sed -i "s|VITE_APP_API_URL=.*$|VITE_APP_API_URL=$VITE_APP_API_URL|g" collectory-ui/config/.env.$ENVIRONMENT
      - sed -i "s|VITE_APP_BASE_URL=.*$|VITE_APP_BASE_URL=$VITE_APP_BASE_URL|g" collectory-ui/config/.env.$ENVIRONMENT
      - sed -i "s|VITE_COMMON_HEADER_HTML=.*$|VITE_COMMON_HEADER_HTML=$VITE_COMMON_HEADER_HTML|g" collectory-ui/config/.env.$ENVIRONMENT
      - sed -i "s|VITE_COMMON_FOOTER_HTML=.*$|VITE_COMMON_FOOTER_HTML=$VITE_COMMON_FOOTER_HTML|g" collectory-ui/config/.env.$ENVIRONMENT
      - sed -i "s|VITE_COMMON_CSS=.*$|VITE_COMMON_CSS=$VITE_COMMON_CSS|g" collectory-ui/config/.env.$ENVIRONMENT
      - sed -i "s|VITE_COMMON_JS=.*$|VITE_COMMON_JS=$VITE_COMMON_JS|g" collectory-ui/config/.env.$ENVIRONMENT
      - sed -i "s|VITE_BANNER_MESSAGES_URL=.*$|VITE_BANNER_MESSAGES_URL=$VITE_BANNER_MESSAGES_URL|g" collectory-ui/config/.env.$ENVIRONMENT
      - sed -i "s|VITE_ENV=.*$|VITE_ENV=$VITE_ENV|g" collectory-ui/config/.env.$ENVIRONMENT
      - cat collectory-ui/config/.env.$ENVIRONMENT
      - cd collectory-ui
  pre_build:
    commands:
      - echo running yarn install...
      - yarn install
  build:
    commands:
      - echo building...
      - yarn build:$ENVIRONMENT

artifacts:
  base-directory: collectory-ui/dist
  files:
    - '**/*'
