[DEFAULT]
PRODUCT_COMPONENT = backend
PIPELINE_STACK_NAME = ala-${PRODUCT_NAME}-${PRODUCT_COMPONENT}-pipeline-${ENVIRONMENT}
HELM_RELEASE_NAME = ala-collectory-${ENVIRONMENT}
EKS_NAMESPACE = apps
ECR_STACK_FILE_PFIX = ecr

AUTO_DEPLOY = true
SLACK_DEPLOY_NOTIFICATION = true
SLACK_ALERT_CHANNEL = testing-deployments

DOCKER_USERNAME = systems@ala.org.au

; --- App config ---
SERVER_URL = https://${WS_SUB_DOMAIN}.${HOSTED_ZONE}
UPLOAD_EXTERNAL_URL_PATH = https://${WS_SUB_DOMAIN}.${HOSTED_ZONE}

SITEMAP_ENABLED = true

DB_URL = jdbc:postgresql://postgresql:5432/collectory
DB_USERNAME = collectory_user
DB_PASSWORD = password

SECURITY_OIDC_ENABLED = true
SECURITY_OIDC_DISCOVERY_URI = https://cognito-idp.ap-southeast-2.amazonaws.com/ap-southeast-2_OOXU9GW39/.well-known/openid-configuration
SECURITY_OIDC_CLIENT_ID =
SECURITY_OIDC_SECRET =
SECURITY_OIDC_SCOPE = "openid profile email ala/attrs ala/roles"
SECURITY_OIDC_USER_ID_CLAIM = cognito:username
SECURITY_OIDC_ROLE_CLAIMS = ala:role
SECURITY_OIDC_LOGOUT_ACTION = COGNITO
SECURITY_OIDC_LOGOUT_URL = https://auth-secure.auth.ap-southeast-2.amazoncognito.com/logout

SECURITY_JWT_ENABLED = true
SECURITY_JWT_DISCOVERY_URI =
SECURITY_JWT_ROLES_FROM_ACCESS_TOKEN = true
SECURITY_JWT_USER_ID_CLAIM = username
SECURITY_JWT_ROLE_CLAIMS = cognito:groups

SECURITY_COOKIE_NAME = ALA-SESSION
SECURITY_COOKIE_DOMAIN = .ala.org.au
SECURITY_COOKIE_DEBUG = false
SECURITY_COOKIE_ROTATE = false
SECURITY_LOGIN_MAX_AGE_DAYS = 30

SECURITY_CORS_ORIGINS = https://${UI_SUB_DOMAIN}.${HOSTED_ZONE},https://${WS_SUB_DOMAIN}.${HOSTED_ZONE}

GBIF_API_URL = https://api.gbif.org/v1/
GBIF_WEBSITE = https://www.gbif.org/
GBIF_REGISTRATION_ENABLED = false
GBIF_REGISTRATION_DRY_RUN = true
GBIF_ENDORSING_NODE_KEY =
GBIF_INSTALLATION_KEY =
GBIF_API_USER =
GBIF_API_PASSWORD =
GBIF_ORPHANS_PUBLISHER_ID =
GBIF_USE_DOI = true
GBIF_DEFAULT_ENTITY_COUNTRY =

BIOCACHE_SERVICES_URL = https://biocache-ws.ala.org.au/ws
BIOCACHE_UI_URL = https://biocache.ala.org.au
LOGGER_URL = https://logger.ala.org.au/service
ALERTS_URL = https://alerts.ala.org.au
SPECIES_LIST_TOOL_URL = https://lists.ala.org.au/speciesListItem/list/
BIE_BASE_URL = https://bie.ala.org.au
SPATIAL_BASE_URL = https://spatial.ala.org.au/
USER_DETAILS_URL = https://api.ala.org.au/userdetails/

HEADER_AND_FOOTER_BASE_URL = https://www.ala.org.au/commonui-bs5-2019
HEADER_AND_FOOTER_VERSION = 2

SKIN_LAYOUT = ala-main
SKIN_HOME_URL = https://www.ala.org.au
SKIN_ORG_NAME_LONG = "Atlas of Living Australia"
SKIN_ORG_NAME_SHORT = Atlas
SKIN_ORG_SUPPORT_EMAIL = support@ala.org.au

GOOGLE_API_KEY =
MAPBOX_ACCESS_TOKEN =

CORS_ENABLED = true
CORS_ALLOWED_ORIGINS = *

SENTRY_DSN =
SENTRY_ENVIRONMENT = ${ENVIRONMENT}
SENTRY_TRACES_SAMPLE_RATE = 0.1

CPU_REQUEST = 500m
MEMORY_REQUEST = 2048Mi
CPU_LIMIT = 2
MEMORY_LIMIT = 2048Mi

[development]
# code pipeline
PIPELINE_STACK_NAME = ala-${PRODUCT_NAME}-${PRODUCT_COMPONENT}-pipeline-${CLEAN_BRANCH}

HELM_RELEASE_NAME = ala-collectory-${CLEAN_BRANCH}

BIOCACHE_SERVICES_URL = https://biocache-ws.test.ala.org.au/ws
BIOCACHE_UI_URL = https://biocache.test.ala.org.au
BIE_BASE_URL = https://bie.test.ala.org.au
SPATIAL_BASE_URL = https://spatial.test.ala.org.au/
USER_DETAILS_URL = https://api.test.ala.org.au/userdetails/

# cookie domain must be empty for non-production (EKS hostnames are not .ala.org.au)
SECURITY_COOKIE_DOMAIN =

[testing]
EKS_NAMESPACE = testing

BIOCACHE_SERVICES_URL = https://biocache-ws.test.ala.org.au/ws
BIOCACHE_UI_URL = https://biocache.test.ala.org.au
BIE_BASE_URL = https://bie.test.ala.org.au
SPATIAL_BASE_URL = https://spatial.test.ala.org.au/
USER_DETAILS_URL = https://api.test.ala.org.au/userdetails/

# cookie domain must be empty for non-production (EKS hostnames are not .ala.org.au)
SECURITY_COOKIE_DOMAIN =

[staging]

[production]

AUTO_DEPLOY = false
SLACK_ALERT_CHANNEL = deployments
